### ISSUE TITLE
Can't access fine-tuned weights through GCS path.

### ISSUE THREAD

**Issue by Yunnglin** [google-research/pix2struct#17]
I can't download the fine-tuned checkpoints.
![image](https://user-images.githubusercontent.com/42505434/217817105-6d65d5e1-f976-486d-99e5-82521bcc136c.png)

Is there another way to download them?

**Comment by kentonl** [comment]
Based on the error message, it looks like the issue is in the destination you specified rather than our bucket. Maybe this Stack Overflow thread will help? https://stackoverflow.com/questions/48776737/how-to-copy-file-from-bucket-gcs-to-my-local-machine

Also, you should know that you don't need to explicitly download the checkpoints if you are using our code. It should be able to directly read from GCS buckets.

**Comment by Yunnglin** [comment]
Thanks for your reply, the problem is solved.
